name: 字体字形问题反馈 / Font glyphs questions feedback
description: >
  提交字形错误、规范性或Unicode码点相关的反馈。 / Feedback on glyph errors, standards, or Unicode code points.
title: "[字形问题 / Glyphs Q.]"
labels: ["字形错误或有改动疑问"]
body:
- type: textarea
  attributes:
    label: 问题字形的码位 / Unicode code point of question glyphs
    description: >
      请输入问题字形的Unicode码位，多个码位用逗号分隔。 
      / Enter the Unicode code point of the question glyphs, separated by commas.
    placeholder: "e.g.: U+21035, U+306CE, ......"
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: 描述问题 / Describe the question
    description: 
    placeholder: | 
      e.g.: 
        1. U+21035: 
            - 问题点 / Question: ......
        2. U+306CE:
            - 问题点 / Question: ......
  validations:
    required: true
- type: textarea
  attributes:
    label: 截图（可选） / Screenshots (optional)
    description: >
      如若遇见无法用文字描述或者用文字描述不明晰的问题，可以添加截图以用来辅助你的反馈。 
      / If you encounter any questions that cannot be described in words or are unclear when described in words, you can add screenshots to assist with your feedback.
  validations:
    required: false
- type: textarea
  attributes:
    label: 其他附加说明（可选） / Other additional notes (optional)
  validations:
    required: false
