name: 其他问题报告 / Other problematic report
description: >
  如果你有其他方面的问题，请在这里反映。 
  / If you have any other problems, please report them here.
title: "[其他问题 / Other problematic]"
labels: ["其他疑问"]
body:
- type: textarea
  attributes:
    label: 问题描述 / Description
    description: 请详细描述您遇到的问题 / Please describe the issue you encountered in detail
  validations:
    required: true
