name: 其他问题或建议反馈 / Other questions or suggestions feedback
description: >
  如果你有其他方面的问题或建议，请在此处反馈。 / If you have any other questions or suggestions, please provide feedback here.
title: "[问题或建议 / Q. & S.]"
labels: ["其他疑问"]
body:
- type: textarea
  attributes:
    label: 具体内容 / Specific content
    description: 
  validations:
    required: true
